apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp2-worker01
  namespace: ocp-compact
  labels:
    cluster-name: ocp-compact
spec:
  config:
    interfaces:
    - name: eth1
      macAddress: 52:54:00:cd:3d:7a
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - ip: 192.168.1.91
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        search:
        - spaz.local
        server:
        - 192.168.1.150
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.1.1
        next-hop-interface: eth1
  interfaces:
    - name: "eth1"
      macAddress: "52:54:00:cd:3d:7a"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp2-worker02
  namespace: ocp-compact
  labels:
    cluster-name: ocp-compact
spec:
  config:
    interfaces:
    - name: eth1
      macAddress: 52:54:00:b4:5f:28
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - ip: 192.168.1.198
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        search:
        - spaz.local
        server:
        - 192.168.1.150
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.1.1
        next-hop-interface: eth1
  interfaces:
    - name: "eth1"
      macAddress: "52:54:00:b4:5f:28"
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp2-worker03
  namespace: ocp-compact
  labels:
    cluster-name: ocp-compact
spec:
  config:
    interfaces:
    - name: eth1
      macAddress: 52:54:00:04:c3:13
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - ip: 192.168.1.86
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        search:
        - spaz.local
        server:
        - 192.168.1.150
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.1.1
        next-hop-interface: eth1
  interfaces:
    - name: "eth1"
      macAddress: "52:54:00:04:c3:13"
