apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: ocp-sno
  namespace: ocp-sno
spec:
  clusterDeploymentRef:
    name: ocp-sno
  imageSetRef:
    name: openshift-4.9.19
  networking:
    clusterNetwork:
    - cidr: 10.128.0.0/14 
      hostPrefix: 23
    machineNetwork:
    - cidr: 192.168.1.0/24
    serviceNetwork:
    - 172.30.0.0/16
  provisionRequirements:
    controlPlaneAgents: 1
  sshPublicKey: 'ssh-rsa ...'
