apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: ocp-sno
  namespace: ocp-sno
  labels:
    cluster-name: ocp-sno
spec:
  config:
    interfaces:
    - name: eth1
      macAddress: 52:54:00:b5:82:03
      type: ethernet
      state: up
      ipv4:
        enabled: true
        address:
        - ip: 192.168.1.135
          prefix-length: 24
        dhcp: false
    dns-resolver:
      config:
        search:
        - spaz.local
        server:
        - 192.168.1.150
    routes:
      config:
      - destination: 0.0.0.0/0
        next-hop-address: 192.168.1.1
        next-hop-interface: eth1
  interfaces:
    - name: "eth1"
      macAddress: "52:54:00:b5:82:03"
