apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ocp-sno
  namespace: ocp-sno
spec:
  clusterRef:
    name: ocp-sno
    namespace: ocp-sno
  sshAuthorizedKey: 'ssh-rsa ...'
  agentLabels: 
    cluster-name: ocp-sno
  pullSecretRef:
    name: assisted-deployment-pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: ocp-sno
